### ISSUE TITLE
Failed to connect KProcessHacker Driver

### ISSUE THREAD

**Issue by wgetnz** [RedSection/OffensivePH#1] opened 2021-05-25 07:39 UTC
C:\Users\max\Desktop>offensiveph.exe -kill 4952
# OffensivePH
-------------------------------------------------
[*] Driver path: C:\Users\max\Desktop\kph.sys
[-] Failed to connect KProcessHacker Driver. Exiting...
[*] Service and file are removed
C:\Users\max\Desktop>

**Comment by OccamsXor** [comment] 2021-05-26 11:05
Can you check if it is executed with Administrator privileges? 
If it is can you check (by using a tool like procmon) if the driver file is created?

**Comment by wgetnz** [comment] 2021-06-07 01:11
> Can you check if it is executed with Administrator privileges?
> If it is can you check (by using a tool like procmon) if the driver file is created?

I am running as an administrator, and I guess the reason for this problem is that the driver does not use SHA2 signatures

**Comment by FurkanAyar** [comment] 2021-06-07 10:14
We have done some changes on repository. Could you provide the current output in order to understand the root cause ?

**Comment by wgetnz** [comment] 2021-06-07 11:31
> We have done some changes on repository. Could you provide the current output in order to understand the root cause ?

An error occurred when compiling

错误	C2086	“NTSTATUS ntstatus”: 重定义	offensiveph	D:\Desktop\OffensivePH-main\offensiveph\offensiveph\main.cpp	56

**Comment by FurkanAyar** [comment] 2021-06-07 11:38
I have fixed the NTSTATUS redefinition error. Could you try it again ?

**Comment by wgetnz** [comment] 2021-06-19 19:11
> I have fixed the NTSTATUS redefinition error. Could you try it again ?

I was on a business trip recently. I’m sorry for the late reply. I have found the cause of the problem. The cause of the problem is that the cmd running as an administrator has disabled the SeDebugPrivilege permission, which may be caused by the windows security policy.
![QQ截图20210620030938](https://user-images.githubusercontent.com/62410571/122653107-2eb62580-d175-11eb-843a-476c69eda003.png)

**Comment by OccamsXor** [comment] 2021-06-24 13:59
Hi @wgetnz ,

@FurkanAyar  has commited EnableSeDebugPrivilege function to the repo which I believe can solve your problem. Do you get the same error when you compile and execute the recent version of offensiveph? 

You can see the commit here: https://github.com/RedSection/OffensivePH/commit/2bd566928874058d9eff95ad8b5b76ea2ff31ebf

**Comment by wgetnz** [comment] 2021-06-28 02:48
> Hi @wgetnz ,
> 
> @FurkanAyar has commited EnableSeDebugPrivilege function to the repo which I believe can solve your problem. Do you get the same error when you compile and execute the recent version of offensiveph?
> 
> You can see the commit here: [2bd5669](https://github.com/RedSection/OffensivePH/commit/2bd566928874058d9eff95ad8b5b76ea2ff31ebf)

It works great. At the same time, I would like to make a suggestion that you can add a function: kill the process according to the process name. I think it is a little troublesome to kill the process using PID. You need to manually query the PID and kill it. In addition, thank you for developing this tool. Great, thank you.

This is translated by me using Google, and the expression may not be very clear, sorry.

**Comment by OccamsXor** [comment] 2021-06-29 07:36
Thank you for the suggestion @wgetnz. I will add that functionality in the next version. I am closing this issue as solved.

**Closed as completed by OccamsXor** 2021-06-29 07:36 UTC
